#!/bin/bash

# Run all SDK examples

DATABASE="rai-sdk-go"
DATABASECLONE="$DATABASE-clone"
ENGINE="rai-sdk-go"

set -x

# reset state
go run delete_database/main.go -d $DATABASECLONE
go run delete_database/main.go -d $DATABASE
go run delete_engine/main.go -e $ENGINE

# engines
go run create_engine/main.go -e $ENGINE --size XS
go run get_engine/main.go -e $ENGINE
go run list_engines/main.go
go run list_engines/main.go --state PROVISIONED
go run list_engines/main.go --state NONSENSE

# databases
go run create_database/main.go -d $DATABASE
go run get_database/main.go -d $DATABASE
go run list_databases/main.go
go run list_databases/main.go --state CREATED
go run list_databases/main.go --state NONSENSE
go run list_edb_names/main.go -d $DATABASE -e $ENGINE
go run list_edbs/main.go -d $DATABASE -e $ENGINE
go run list_model_names/main.go -d $DATABASE -e $ENGINE
go run list_models/main.go -d $DATABASE -e $ENGINE
go run get_model/main.go -d $DATABASE -e $ENGINE -m stdlib

# exec
QUERY='def output(x, x2, x3, x4): {1; 2; 3; 4; 5}(x) and x2 = x^2 and x3 = x^3 and x4 = x^4'
go run execute/main.go -d $DATABASE -e $ENGINE -c "$QUERY"
go run execute/main.go -d $DATABASE -e $ENGINE -c "$QUERY" --readonly

# load model
go run load_model/main.go -d $DATABASE -e $ENGINE -f hello.rel
go run get_model/main.go -d $DATABASE -e $ENGINE -m hello
go run list_models/main.go -d $DATABASE -e $ENGINE
go run list_model_names/main.go -d $DATABASE -e $ENGINE
go run delete_model/main.go -d $DATABASE -e $ENGINE -m hello
go run list_model_names/main.go -d $DATABASE -e $ENGINE

# load-csv
go run list_edbs/main.go -d $DATABASE -e $ENGINE
go run load_csv/main.go -d $DATABASE -e $ENGINE -r sample_csv -f sample.csv
go run execute/main.go -d $DATABASE -e $ENGINE -c sample_csv
go run load_csv/main.go -d $DATABASE -e $ENGINE -r sample_no_header_csv -f sample_no_header.csv --headerrow=0
go run execute/main.go -d $DATABASE -e $ENGINE -c sample_no_header_csv
go run load_csv/main.go -d $DATABASE -e $ENGINE -r sample_alt_syntax_csv -f sample_alt_syntax.csv --delim='|' --quotechar="\"'\""
go run execute/main.go -d $DATABASE -e $ENGINE -c sample_alt_syntax_csv
go run list_edbs/main.go -d $DATABASE -e $ENGINE

# load-json
go run load_json/main.go -d $DATABASE -e $ENGINE -r sample_json -f sample.json
go run execute/main.go -d $DATABASE -e $ENGINE -c sample_json
go run list_edbs/main.go -d $DATABASE -e $ENGINE

# clone database
go run delete_database/main.go -d $DATABASE
go run create_database/main.go -d $DATABASE
go run load_json/main.go -d $DATABASE -e $ENGINE -r sample_json -f sample.json
go run load_model/main.go -d $DATABASE -e $ENGINE -f hello.rel
go run clone_database/main.go -d $DATABASECLONE -s $DATABASE
go run list_databases/main.go
go run get_database/main.go -d $DATABASECLONE
go run list_edbs/main.go -d $DATABASECLONE -e $ENGINE
go run list_models/main.go -d $DATABASECLONE -e $ENGINE
go run get_model/main.go -d $DATABASECLONE -e $ENGINE -m hello

# oauth-clients
CLIENTNAME="sdk-test-client"
CLIENTID=`go run find_oauth_client/main.go -n $CLIENTNAME | jq -r '.id'`
if [[ "$CLIENTID" != null ]]; then
go run delete_oauth_client/main.go --id $CLIENTID
fi
go run list_oauth_clients/main.go
go run create_oauth_client/main.go -n $CLIENTNAME
go run list_oauth_clients/main.go
go run find_oauth_client/main.go -n $CLIENTNAME
CLIENTID=`go run find_oauth_client/main.go -n $CLIENTNAME | jq -r '.id'`
go run get_oauth_client/main.go --id $CLIENTID
go run delete_oauth_client/main.go --id $CLIENTID
go run list_oauth_clients/main.go

# users
EMAIL=sdk-test@relational.ai
USERID=`go run find_user/main.go -e $EMAIL | jq -r '.id'`
if [[ "$USERID" != null ]]; then
go run delete_user/main.go --id "$USERID"
fi
go run list_users/main.go
go run create_user/main.go -e $EMAIL
go run list_users/main.go
go run find_user/main.go -e $EMAIL
USERID=`go run find_user/main.go -e $EMAIL | jq -r '.id'`
go run get_user/main.go --id "$USERID"
go run disable_user/main.go --id "$USERID"
go run enable_user/main.go --id "$USERID"
go run update_user/main.go --id "$USERID" --status INACTIVE
go run update_user/main.go --id "$USERID" --status ACTIVE
go run update_user/main.go --id "$USERID" --role admin --role user
go run update_user/main.go --id "$USERID" --role user --status INACTIVE
go run update_user/main.go --id "$USERID"
go run delete_user/main.go --id "$USERID"
go run list_users/main.go

# cleanup
go run delete_database/main.go -d $DATABASECLONE
go run delete_database/main.go -d $DATABASE
go run delete_engine/main.go -e $ENGINE
CLIENTID=`go run find_oauth_client/main.go -n $CLIENTNAME | jq -r '.id'`
if [[ "$CLIENTID" != null ]]; then
go run delete_oauth_client/main.go --id $CLIENTID
fi
USERID=`go run find_user/main.go -e $EMAIL | jq -r '.id'`
if [[ "$USERID" != null ]]; then
go run delete_user --id "$USERID"
fi
